baseurl = "/"
languageCode = "en-us"
title = "Classic"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = false
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Data Science"
    url = "/menu/data-science/"
    weight = 1
[[menu.main]]
    name = "Sales"
    url = "/post/2017/11/21/everything-about-sales/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.feed]]
    name = "Contact"
    url = "/post/2012/01/23/contact/"

[params]
    description = "A simple, minimal blog for those who love text."
    footer = "Open-Source | [Github](https://github.com/goodroot/hugo-classic) | [Twitter](https://twitter.com/thegoodroot)"
    mathjax = true
